// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltaxxkxtvvckakebmnpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0YXh4a3h0dnZja2FrZWJtbnB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3OTI3NDAsImV4cCI6MjA2NDM2ODc0MH0.BQ24rCINQ5yHmDLzSxAL_GI8mLtK32Wwn0l6xY0NdgU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);